### ISSUE TITLE
Question. KeyStore and TrustStore automatic generation.

### ISSUE THREAD

**Issue by dzheltuk** [HewlettPackard/oneview-sdk-java#12]
Hello, do you have the some sort of the script that helps user to generate Store files automatically.
Which way is the best to create that one? Curl usage possibly? 

curl -X POST -H "Content-Type:application/json" -d '{"userName":"{USERNAME}","password":"{PASSWORD}"}' \
-k https://{HOST}/rest/login-sessions

Thank you!

Dmitriy

**Comment by lhsvobodaj** [comment]
Hi @dzheltuk 

In the latest SDK release (3.0.0) we removed the need of creating a KeyStore file. Besides, now we only need the OneView server CA certificate in order to establish a secure connection with the OneView appliance.
About the script, we have also included a script called `build-truststore.sh`, which can be found inside the project's bin folder. The script is only available for Linux (if you are using Windows, you can use the script as a reference).

**Comment by dzheltuk** [comment]
Thanks you! Looks good for me.
