### ISSUE TITLE
Getting all Storage Volumes using REST API

### ISSUE THREAD

**Issue by pallavidn** [HewlettPackard/oneview-sdk-java#6]
I have more than 10 storage volumes defined in Oneview, however, StorageVolumeCollection.getMembers() returns only 10. Don't see a way to get more than 10 using the java sdk.

**Comment by filipe-kovalski** [comment]
Hi @pallavidn , thanks for the feedback.
We are addressing this issue.

**Comment by esara** [comment]
There are a couple observations; the OneView REST api should return all instances of a resource type based on the count=-1 argument in the API call, but this does not work.
On the other hand, specifying a larger number than the total count of instances as count=X will return all instances.

**Comment by esara** [comment]
Separately from this, the java API getAllXXX methods should return all instances, so I propose to add a count=max integer, which based on our testing works correctly in OneView environments (having more then 5 interconnects, 10 storage volumes, 32 blades, etc...)

**Comment by esara** [comment]
Please comment on: https://github.com/vmturbo/oneview-sdk-java/commit/84874385fb1dd4a4c1c49a4ace08148082deb807

**Comment by esara** [comment]
I had another session with a customer and even after specifying a large count=XX argument, the OneView API only returns back the first 10 interconnects (more then the 5 by default, but not all of them).
Besides paging in the SDK, I dont see how this can be solved - I really think the OneView REST API needs handle the API requests as documented (either count=-1 for all the entities or at least count=XX returning XX entities - even if XX>10)

**Comment by ghost** [comment]
Hello.... 

The pagination is required for some resources due to time required to build the response for the request.  In some large resources, building the response for all resources will result in processing a response longer than allowed in our framework.  (We can't have a request take too long.)  Thus the limits are present to assure that the user will receive at least some of the resources in a timely manner.

The nextPageUri and previousPageUri will allow the traversal of the all the resources.

**Comment by esara** [comment]
Hi,

I reverted my previous change and came up with a new one that is paging through the API calls and combines them into a single response for the getAll...() methods, please see:
https://github.com/vmturbo/oneview-sdk-java/commit/31d202bfaeb569807c59f1b60a2e2df9278364f6

I succesfully tested this in-house with more then 10 interconnects
I am happy to push this upstream..

Endre

**Comment by lhsvobodaj** [comment]
@esara 

Thanks for your feedback and for your solution to the `getAll()` issue. The getAll behavior was fixed in the 3.0.0 version (latest version recently released). It differs a bit from your solution since we did not use the field `nextPageUri`to check whether there are more items to retrieve or not. Instead, we use the values for total and count since we also found some issues when using the `nextPageUri` field.

Is it possible for you to update the SDK to the latest version? In case the update is an alternative, we encourage you to do so. If it is not, please let us know.

**Comment by CintiaLopes** [comment]
Closing since issue is fixed since v3.0.0.

Thanks again @esara for your support fixing the issue, we appreciate that.

Regards,
Cintia
